window:
  #padding:
    #x: 10
    #y: 10
  class:
    instance: Alacritty
    general: Alacritty
  opacity: 0.8

scrolling:
  history: 10000
  multiplier: 3

font:
  normal:
    family: Hack Nerd Font
    style:  Regular
  bold:
    family: Hack Nerd Font
    style:  Bold
  italic:
    family: Hack Nerd Font
    style:  Italic
  bold_italic:
    family: Hack Nerd Font
    style: Bold Italic
  size: 12
draw_bold_text_with_bright_colors: true

selection:
  save_to_clipboard: true
import:
  - ~/.config/alacritty/moon.yml
